# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    body_converter:
        enabled: true
        validate: true
    serializer:
        serialize_null: true
    param_fetcher_listener:  true
    allowed_methods_listener:  true
    routing_loader:
        default_format: json
        include_format: false
    view:
        view_response_listener: true
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: 'json' }
            - { path: '^/', stop: true }
